global:
  scrape_interval: 5s # Collect metrics every 5 seconds

scrape_configs:
  - job_name: 'learning_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['learning_english_api:5000'] # Collect metrics from the API