apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: alijan123a/learning_english_api:latest
          ports:
            - containerPort: 5000
          env:
            - name: API_KEY
              value: "7yrnhzcTJk3vFd07nzSROA==vRxkEynraZ3Flbyn"
          args:
            - python app.py

        - name: redis-container
          image: ghcr.io/aut-cloud-computing-fall-2024/sonic
          ports:
            - containerPort: 6379
