name: Docker Image CI/CD for Phase 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: alijan123a
        password: Alijan@123a

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t alijan123a/learning_english_api:latest ./phase1

    # Step 4: Push the Docker image
    - name: Push Docker image
      run: |
        docker push alijan123a/learning_english_api:latest
